resources:
  - name: car_app
    type: GitRepo
    configuration:
      gitProvider: ranjithr_github
      path: ranjithrs/carbot
      branches:
        include: master
  - name: my
    type: GitRepo
    configuration:
      gitProvider: ranjithr_github
      path: ranjithrs/carbot
      branches:
        include: master    
  - name: myFile
    type: RemoteFile
    configuration:
      source: dummyFileServer
        
pipelines:
  - name: simple_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: car_app
        execution:
          onExecute:
            - printenv
            - add_pipeline_variable pipeline_var=1
            - add_run_variable run_var="hello"

      - name: step_2
        type: Bash
        configuration:
          integrations:
            - name: art
          inputSteps:
            - name: step_1
          outputResources:
            - name: myFile
          runtime:
            type: image
            image:
              auto:
                language: java
        execution:
          onExecute:
            - printenv
            - if [ $(($pipeline_var % 2)) -eq 0 ] then echo $run_var + "world" else echo $run_var + "universe"
            - $pipeline_var++

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
          inputResources:
            - name: myFile
              trigger: false
          runtime:
            type: image
            image:
              auto:
                language: nodejs
        execution:
          onExecute:
            - printenv

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
            - name: step_3
          runtime:
            type: image
            image:
              auto:
                language: go             
        execution:
          onExecute:
            - printenv
